Use correct tag for test image
Signed-off-by: Ivan Kavaldzhiev <ivankavaldzhiev@gmail.com>

diff --git a/.github/workflows/acceptance.yaml b/.github/workflows/acceptance.yaml
--- a/.github/workflows/acceptance.yaml
+++ b/.github/workflows/acceptance.yaml
@@ -75,14 +75,14 @@ jobs:
         run: ./gradlew test:build -x test
 
       - name: Build Mirror Node Test Docker image
-        run: docker build -t gcr.io/mirrornode/hedera-mirror-test:"${{ github.base_ref }}" -f test/Dockerfile ./test
+        run: docker build -t gcr.io/mirrornode/hedera-mirror-test:pr-test -f test/Dockerfile ./test
 
       - name: Setup Solo Cluster
         run: |
           kind create cluster -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to create Kind cluster"; exit 1; }
           solo init || { echo "Failed to initialize Solo"; exit 1; }
           solo cluster-ref connect --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --context kind-"${SOLO_CLUSTER_NAME}" || { echo "Failed to connect to cluster"; exit 1; }
-          kind load docker-image gcr.io/mirrornode/hedera-mirror-test:"${{ github.base_ref }}" -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to load docker image"; exit 1; }
+          kind load docker-image gcr.io/mirrornode/hedera-mirror-test:pr-test -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to load docker image"; exit 1; }
           solo deployment create --deployment "${SOLO_DEPLOYMENT}" --namespace "${SOLO_NAMESPACE}" || { echo "Failed to create deployment"; exit 1; }
           solo deployment add-cluster --deployment "${SOLO_DEPLOYMENT}" --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --num-consensus-nodes 1 || { echo "Failed to add cluster to deployment"; exit 1; }
           solo cluster-ref setup --cluster-ref kind-"${SOLO_CLUSTER_NAME}" || { echo "Failed to setup cluster"; exit 1; }
@@ -94,10 +94,11 @@ jobs:
           cat <<EOF > temp-values.yaml
           global:
             image:
-              tag: "${{ github.base_ref }}"
               pullPolicy: IfNotPresent
 
           test:
+            image:
+              tag: pr-test
             config:
               hiero:
                 mirror:
