Stabilize acceptance tests
Signed-off-by: Ivan Kavaldzhiev <ivankavaldzhiev@gmail.com>

diff --git a/.github/workflows/acceptance.yaml b/.github/workflows/acceptance.yaml
--- a/.github/workflows/acceptance.yaml
+++ b/.github/workflows/acceptance.yaml
@@ -79,6 +79,26 @@ jobs:
 
       - name: Setup Solo Cluster
         run: |
+          kind create cluster -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to create Kind cluster"; exit 1; }
+          kind load docker-image hiero-mirror-node:pr-test -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to load Docker image into Kind"; exit 1; }
+          solo init || { echo "Failed to initialize Solo"; exit 1; }
+          solo cluster-ref connect --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --context kind-"${SOLO_CLUSTER_NAME}" || { echo "Failed to connect to cluster"; exit 1; }
+          solo deployment create --deployment "${SOLO_DEPLOYMENT}" --namespace "${SOLO_NAMESPACE}" || { echo "Failed to create deployment"; exit 1; }
+          solo deployment add-cluster --deployment "${SOLO_DEPLOYMENT}" --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --num-consensus-nodes 1 || { echo "Failed to add cluster to deployment"; exit 1; }
+          solo cluster-ref setup --cluster-ref kind-"${SOLO_CLUSTER_NAME}" || { echo "Failed to setup cluster"; exit 1; }
+          solo node keys --gossip-keys --tls-keys --deployment "${SOLO_DEPLOYMENT}" -i node1 || { echo "Failed to generate keys"; exit 1; }
+          solo network deploy --deployment "${SOLO_DEPLOYMENT}" || { echo "Failed to deploy network"; exit 1; }
+          solo node setup --deployment "${SOLO_DEPLOYMENT}" -i node1 || { echo "Failed to setup node"; exit 1; }
+          solo node start --deployment "${SOLO_DEPLOYMENT}" -i node1 || { echo "Failed to start node"; exit 1; }
+
+          solo account create --deployment "${SOLO_DEPLOYMENT}" --hbar-amount 1000000 --generate-ecdsa-key --set-alias > account_create.log || { echo "Failed to create account"; exit 1; }
+          OPERATOR_ID=$(grep "accountId" account_create.log | awk '{print $2}' | sed 's/"//g'| sed 's/,//g')
+          rm account_create.log
+
+          solo account get --deployment "${SOLO_DEPLOYMENT}" --account-id "${OPERATOR_ID}" --private-key > account_get.log || { echo "Failed to get account"; exit 1; }
+          OPERATOR_KEY=$(grep "privateKey" account_get.log | awk '{print $2}' | sed 's/"//g'| sed 's/,//g')  || { echo "Failed to get account"; exit 1; }
+          rm account_get.log
+
           cat <<EOF > temp-values.yaml
           global:
             image:
@@ -91,19 +111,10 @@ jobs:
                   test:
                     acceptance:
                       network: OTHER
+                      operatorId: "${{ env.OPERATOR_ID }}"
+                      operatorKey: "${{ env.OPERATOR_KEY }}"
           EOF
 
-          kind create cluster -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to create Kind cluster"; exit 1; }
-          kind load docker-image hiero-mirror-node:pr-test -n "${SOLO_CLUSTER_NAME}" || { echo "Failed to load Docker image into Kind"; exit 1; }
-          solo init || { echo "Failed to initialize Solo"; exit 1; }
-          solo cluster-ref connect --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --context kind-"${SOLO_CLUSTER_NAME}" || { echo "Failed to connect to cluster"; exit 1; }
-          solo deployment create --deployment "${SOLO_DEPLOYMENT}" --namespace "${SOLO_NAMESPACE}" || { echo "Failed to create deployment"; exit 1; }
-          solo deployment add-cluster --deployment "${SOLO_DEPLOYMENT}" --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --num-consensus-nodes 1 || { echo "Failed to add cluster to deployment"; exit 1; }
-          solo cluster-ref setup --cluster-ref kind-"${SOLO_CLUSTER_NAME}" || { echo "Failed to setup cluster"; exit 1; }
-          solo node keys --gossip-keys --tls-keys --deployment "${SOLO_DEPLOYMENT}" -i node1 || { echo "Failed to generate keys"; exit 1; }
-          solo network deploy --deployment "${SOLO_DEPLOYMENT}" || { echo "Failed to deploy network"; exit 1; }
-          solo node setup --deployment "${SOLO_DEPLOYMENT}" -i node1 || { echo "Failed to setup node"; exit 1; }
-          solo node start --deployment "${SOLO_DEPLOYMENT}" -i node1 || { echo "Failed to start node"; exit 1; }
           solo mirror-node deploy --deployment "${SOLO_DEPLOYMENT}" -f=temp-values.yaml --cluster-ref kind-"${SOLO_CLUSTER_NAME}" --pinger || { echo "Failed to deploy mirror node"; exit 1; }
 
           echo "Solo cluster setup completed successfully!"
